filebrowser/urls.py
# As of version 3.4, all urls moved to FileBrowserSite class in filebrowser.sites
# This file will be removed with version 3.6

filebrowser/models.py
# This file is only necessary for the tests to work

filebrowser/forms.py
# coding: utf-8

# PYTHON IMPORTS
import os
import re

# DJANGO IMPORTS
from django import forms
from django.utils.translation import ugettext_lazy as _

# FILEBROWSER IMPORTS
from filebrowser.settings import FOLDER_REGEX
from filebrowser.utils import convert_filename

ALNUM_NAME_RE = re.compile(FOLDER_REGEX, re.U)

# CHOICES
TRANSPOSE_CHOICES = (
    ("", u"-----"),
    ("0", _(u"Flip horizontal")),
    ("1", _(u"Flip vertical")),
    ("2", _(u"Rotate 90° CW")),
    ("4", _(u"Rotate 90° CCW")),
    ("3", _(u"Rotate 180°")),
)


class CreateDirForm(forms.Form):
    """
    Form for creating a folder.
    """

    name = forms.CharField(widget=forms.TextInput(attrs=dict({'class': 'vTextField'}, max_length=50, min_length=3)), label=_(u'Name'), help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)

    def __init__(self, path, *args, **kwargs):
        self.path = path
        self.site = kwargs.pop("filebrowser_site", None)
        super(CreateDirForm, self).__init__(*args, **kwargs)

    def clean_name(self):
        "validate name"
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not ALNUM_NAME_RE.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            # Folder must not already exist.
            if self.site.storage.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['name']))):
                raise forms.ValidationError(_(u'The Folder already exists.'))
        return convert_filename(self.cleaned_data['name'])


class ChangeForm(forms.Form):
    """
    Form for renaming a file/folder.
    """

    custom_action = forms.ChoiceField(label=_(u'Actions'), required=False)
    name = forms.CharField(widget=forms.TextInput(attrs=dict({'class': 'vTextField'}, max_length=50, min_length=3)), label=_(u'Name'), help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)

    def __init__(self, *args, **kwargs):
        self.path = kwargs.pop("path", None)
        self.fileobject = kwargs.pop("fileobject", None)
        self.site = kwargs.pop("filebrowser_site", None)
        super(ChangeForm, self).__init__(*args, **kwargs)

        # Initialize choices of custom action
        choices = [("", u"-----")]
        for name, action in self.site.applicable_actions(self.fileobject):
            choices.append((name, action.short_description))
        self.fields['custom_action'].choices = choices

    def clean_name(self):
        "validate name"
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not ALNUM_NAME_RE.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            #  folder/file must not already exist.
            if self.site.storage.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['name']))) and os.path.join(self.path, convert_filename(self.cleaned_data['name'])) != self.fileobject.path:
                raise forms.ValidationError(_(u'The Folder already exists.'))
            elif self.site.storage.isfile(os.path.join(self.path, convert_filename(self.cleaned_data['name']))) and os.path.join(self.path, convert_filename(self.cleaned_data['name'])) != self.fileobject.path:
                raise forms.ValidationError(_(u'The File already exists.'))
        return convert_filename(self.cleaned_data['name'])

filebrowser/views.py
# As of version 3.4, all views moved to FileBrowserSite class in filebrowser.sites
# This file will be removed with version 3.6

filebrowser/templates/filebrowser/createdir.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load admin_static i18n fb_tags fb_csrf %}

<!-- STYLESHEETS -->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "filebrowser/css/filebrowser.css" %}" />
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}grp-change-form grp-filebrowser{% if query.pop %} grp-popup{% endif %}{% endblock %}
{% block content-class %}{% endblock %}

<!-- BREADCRUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="grp-content-container">
    <form action="{% query_string '' 'p' %}" method="post">{% fb_csrf_token %}
        {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
        <fieldset class="grp-module aligned">
            <div class="grp-row {% if form.dir_name.errors %}grp-errors{% endif %}">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label class="required" for="id_dir_name">{{ form.name.label }}</label></div>
                    <div class="c-2">
                        {{ form.name }}
                        {% if form.dir_name.errors %}<ul class="errorlist">{{ form.name.errors }}</ul>{% endif %}
                        <p class="grp-help">
                            {{ form.name.help_text|safe }}
                            {% if settings_var.NORMALIZE_FILENAME or settings_var.CONVERT_FILENAME %}
                                <br />
                                {% if settings_var.NORMALIZE_FILENAME %}
                                    {% trans "The Name will be normalized by converting or stripping all non-standard characters." %} <br />
                                {% endif %}
                                {% if settings_var.CONVERT_FILENAME %}
                                    {% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}
                                {% endif %}
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </fieldset>
        <footer class="grp-module grp-submit-row grp-fixed-footer">
            <header style="display:none"><h1>Submit Options</h1></header>
            <ul>
                <li><input type="submit" value="{% trans 'Submit' %}" class="grp-button grp-default" /></li>
            </ul>
        </div>
    </form>
</div>
{% endblock %}

filebrowser/templates/filebrowser/custom_field.html
{% load i18n fb_versions %}
<input id="{{ final_attrs.id }}" type="text" class="vFileBrowseField{% if final_attrs.class %} {{ final_attrs.class }}{% endif %}" name="{{ final_attrs.name }}" value="{{ value.path }}" /><a href="javascript:FileBrowser.show('{{ final_attrs.id }}', '{{ url }}?pop=1{% if final_attrs.directory %}&amp;dir={{ final_attrs.directory|urlencode|urlencode }}{% endif %}{% if final_attrs.format %}&amp;type={{ final_attrs.format }}{% endif %}');" class="fb_show"></a>
{% if value.filetype == "Image" and value.exists %}
{% version_object value.path final_attrs.ADMIN_THUMBNAIL as thumbnail_version %}
{% if thumbnail_version %}
<p class="preview" id="preview_{{ final_attrs.id }}">
    <a href="{{ value.url }}" target="_blank" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" src="{{ thumbnail_version.url }}" class="preview" />
    </a>
</p>
{% else %}
<p class="preview" id="preview_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endif %}
{% else %}
<p class="preview" id="preview_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endif %}
{% if value and not value.exists %}
<ul class="errorlist"><li>{% trans "File not found" %}</li></ul>
{% endif %}

filebrowser/templates/filebrowser/delete_confirm.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load admin_static i18n fb_tags fb_versions %}
{% load url from future %}

<!-- STYLESHEETS -->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "filebrowser/css/filebrowser.css" %}" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block javascripts %}
    {{ block.super }}
    {{ media }}
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}grp-delete-confirmation grp-filebrowser{% if query.pop %} grp-popup{% endif %}{% endblock %}
{% block content-class %}{% endblock %}

<!-- BREADCRBUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
    <div class="g-d-c">
        <div class="grp-group">
            <h2>{% blocktrans with fileobject.filename as escaped_object %}Are you sure you want to delete "{{ escaped_object }}"? All of the following items will be deleted:{% endblocktrans %}</h2>
            <ul class="grp-nested-list">
                <li>{{ fileobject.filename }}</li>
            </ul>
            {% if filelisting %}
                <ul class="grp-nested-list">
                    {% for item in filelisting %}
                        <li>{{ item.path_relative_directory }}</li>
                    {% endfor %}
                <ul>
            {% endif %}
            {% if additional_files %}
                <ul class="grp-nested-list">
                    <li>{% blocktrans with additional_files as escaped_object %}... and {{ escaped_object }} more Files.{% endblocktrans %}</li>
                </ul>
            {% endif %}
        </div>
        <footer class="grp-module grp-submit-row grp-fixed-footer">
            <header style="display:none"><h1>Submit Options</h1></header>
            <ul {% if is_popup %}style="overflow: auto;"{% endif %}>
                <li class="grp-float-left"><a href="{% url 'filebrowser:fb_detail' %}{% query_string %}" class="grp-button grp-cancel-link">{% trans "Cancel" %}</a></li>
                <li><a href="{% url 'filebrowser:fb_delete' %}{% query_string %}" class="grp-button">{% trans "Yes, I'm sure" %}</a></li>
            </ul>
        </footer>
    </div>
{% endblock %}

filebrowser/templates/filebrowser/detail.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load admin_static i18n fb_tags fb_versions %}
{% load url from future %}

<!-- STYLESHEETS -->
{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "filebrowser/css/filebrowser.css" %}" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript">
    (function($){
        $(document).ready(function() {
            $("div#grp-content-container .grp-collapse").grp_collapsible({
                on_init: function(elem, options) {
                    // open collapse (and all collapse parents) in case of errors
                    if (elem.find("ul.grp-errorlist").length > 0) {
                        elem.removeClass("grp-closed")
                            .addClass("grp-open");
                        elem.parents(".grp-collapse")
                            .removeClass("grp-closed")
                            .addClass("grp-open");
                    }
                }
            });
        });
    })(grp.jQuery);
    </script>
    {{ media }}
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}grp-change-form grp-filebrowser{% if query.pop %} grp-popup{% endif %}{% endblock %}
{% block content-class %}{% endblock %}

<!-- BREADCRBUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="grp-content-container">
    <form action="{% query_string "" "filter_date,filter_type,q,p" %}" method="post">{% csrf_token %}
        {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
        <fieldset class="grp-module">
            <div class="grp-row {% if form.name.errors %}grp-errors{% endif %}">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label class="required" for="id_name">{{ form.name.label }}</label></div>
                    <div class="c-2">
                        {{ form.name }}
                        {% if form.name.errors %}<ul class="errorlist">{{ form.name.errors }}</ul>{% endif %}
                        {% if form.name.help_text %}<p class="grp-help">{{ form.name.help_text|safe }}</p>{% endif %}
                    </div>
                </div>
            </div>
        </fieldset>
        {% if fileobject.filetype == "Image" %}
        <fieldset class="grp-module grp-collapse grp-open">
            <h2 class="grp-collapse-handler">{% trans "Edit" %}</h2>
            <div class="grp-row {% if form.custom_action.errors %}grp-errors{% endif %}">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label class="required" for="id_custom_action">{{ form.custom_action.label }}</label></div>
                    <div class="c-2">
                        {{ form.custom_action }}
                        {% if form.custom_action.errors %}<ul class="errorlist">{{ form.custom_action.errors }}</ul>{% endif %}
                        {% if form.custom_action.help_text %}<p class="help">{{ form.custom_action.help_text|safe }}</p>{% endif %}
                    </div>
                </div>
            </div>
        </fieldset>
        {% endif %}
        {% if fileobject.filetype == "Folder" %}
        <fieldset class="grp-module grp-collapse grp-open">
            <h2 class="grp-collapse-handler">{% trans "Folder Information" %}</h2>
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>{% trans "Date" %}</label></div>
                    <div class="c-2">
                        <p class="grp-text">
                            {{ fileobject.datetime|date:"N j, Y" }}
                        </p>
                    </div>
                </div>
            </div>
        </fieldset>
        {% endif %}
        {% if fileobject.filetype != "Folder" %}
        <fieldset class="grp-module grp-collapse grp-open">
            <h2 class="grp-collapse-handler">{% trans "File Information" %}</h2>
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>{% trans "URL" %}</label></div>
                    <div class="c-2">
                        <p class="grp-text">
                            <a href="{{ fileobject.url }}">{{ fileobject.url }}</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>{% trans "Filesize" %}</label></div>
                    <div class="c-2">
                        <p class="grp-text">
                            {{ fileobject.filesize|filesizeformat }}
                        </p>
                    </div>
                </div>
            </div>
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>{% trans "Date" %}</label></div>
                    <div class="c-2">
                        <p class="grp-text">
                            {{ fileobject.datetime|date:"N j, Y" }}
                        </p>
                    </div>
                </div>
            </div>
            {% if fileobject.filetype == "Image" %}
                <div class="grp-row">
                    <div class="l-2c-fluid l-d-4">
                        <div class="c-1"><label>{% trans "Size" %}</label></div>
                        <div class="c-2">
                            <p class="grp-text">
                                {{ fileobject.width }} x {{ fileobject.height }} px
                            </p>
                        </div>
                    </div>
                </div>
            {% endif %}
        </fieldset>
        {% endif %}
        {% if fileobject.filetype == "Image" %}
        <fieldset class="grp-module grp-collapse grp-open">
            <h2 class="grp-collapse-handler">{% trans "Image Versions" %}</h2>
            {% if settings_var.ADMIN_THUMBNAIL %}
            <div class="grp-row">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1"><label>{% trans "Thumbnail" %}</label></div>
                    <div class="c-2">
                        <img src="{% version fileobject.path settings_var.ADMIN_THUMBNAIL %}" title="{% trans 'View Image' %}" />
                    </div>
                </div>
            </div>
            {% endif %}
            {% if settings_var.ADMIN_VERSIONS %}
                {% for version in settings_var.ADMIN_VERSIONS %}
                    {% version_object fileobject version as image_version %}
                    {% version_setting version %}
                    <div class="grp-row">
                        <div class="l-2c-fluid l-d-4">
                            <div class="c-1"><label>{{ version_setting.verbose_name }}</label></div>
                            <div class="c-2">
                                <img src="{{ image_version.url }}" />
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </fieldset>
        {% endif %}
        <footer class="grp-module grp-submit-row grp-fixed-footer">
            <header style="display:none"><h1>Submit Options</h1></header>
            <ul>
                <li class="grp-float-left"><a href="{% url 'filebrowser:fb_delete_confirm' %}{% query_string %}" class="grp-button grp-delete-link">{% trans "Delete" %}</a></li>
                <li><input type="submit" value="{% trans 'Save' %}" class="grp-button grp-default" /></li>
                <li><input type="submit" value="{% trans 'Save and continue editing' %}" class="grp-button" name="_continue" /></li>
            </ul>
        </footer>
    </form>
</div>
{% endblock %}

filebrowser/templates/filebrowser/include/_response.html
{{ response }}

filebrowser/templates/filebrowser/include/breadcrumbs.html
{% load i18n fb_tags %}
{% load url from future %}
<ul class="grp-horizontal-list">
    {% if not query.pop %}
        <li><a href="{% url 'admin:index' %}">{% trans "Home" %}</a></li>
    {% endif %}
    {% if breadcrumbs or breadcrumbs_title %}
        <li><a href="{% url 'filebrowser:fb_browse' %}{% query_string "" "q,dir,filename,p" %}">{% trans 'FileBrowser' %}</a></li>
    {% else %}
        <li>{% trans 'FileBrowser' %}</li>
    {% endif %}
    {% for item in breadcrumbs %}
        {% if not forloop.last %}
            <li><a href="{% url 'filebrowser:fb_browse' %}{% query_string "" "q,dir,filename,p" %}&amp;dir={{ item.1|urlencode }}">{{ item.0 }}</a></li>
        {% else %}
            {% if breadcrumbs_title %}
                <li><a href="{% url 'filebrowser:fb_browse' %}{% query_string "" "q,dir,filename,p" %}&amp;dir={{ item.1|urlencode }}">{{ item.0 }}</a></li>
            {% else %}
                <li>{{ item.0 }}</li>
            {% endif %}
        {% endif %}
    {% endfor %}
    {% if breadcrumbs_title %}
        <li>{{ breadcrumbs_title }}</li>
    {% endif %}
</ul>

filebrowser/templates/filebrowser/include/filelisting.html
{% load i18n fb_tags fb_versions %}
{% load url from future %}

{% for fileobject in page.object_list %}
    
    <!-- THUMBNAIL-VERSION FOR IMAGE-OBJECT -->
    {% if fileobject.filetype == "Image" %}
        {% version_object fileobject settings_var.ADMIN_THUMBNAIL as thumbnail_version %}
    {% endif %}
    
    <tr class="grp-row grp-row-even{% if fileobject.filetype == "Folder" %} fb_folder{% endif %}">
        
        <!-- FILESELECT FOR FILEBROWSEFIELD -->
        {% if query.pop == "1" %}
            <td class="fb_icon">
                {% selectable fileobject.filetype query.type %}
                {% if selectable %}
                    <!-- select original -->
                    <button class="grp-button fb_selectlink" onclick="FileSubmit('{{ fileobject.path }}', '{{ fileobject.url }}', '{{ thumbnail_version.url }}', '{{ fileobject.filetype }}');">{% trans "Select" %}</button>
                    <!-- select versions -->
                    {% if fileobject.filetype == "Image" and settings_var.ADMIN_VERSIONS %}
                        <div class="grp-pulldown-versions-container">
                            <a href="javascript://" class="grp-pulldown-versions-handler" title="{% trans "Versions" %}">&nbsp;</a>
                            <ul class="grp-pulldown-versions">
                                {% for version in settings_var.ADMIN_VERSIONS %}
                                    {% version_setting version %}
                                    <li><a href="{% url 'filebrowser:fb_version' %}{% query_string '' 'filename, dirname' %}&amp;dir={{ fileobject.dirname|urlencode }}&amp;filename={{ fileobject.filename|urlencode }}&amp;version={{ version }}" title="">{{ version_setting.verbose_name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                {% else %}
                    &nbsp;
                {% endif %}
            </td>
        {% endif %}
        
        <!-- FILESELECT FOR RTE/TINYMCE -->
        <!-- we need to use the absolute url here -->
        {% if query.pop == "2" %}
            <td class="fb_icon">
                {% selectable fileobject.filetype query.type %}
                {% if selectable %}
                    <!-- select original -->
                    <button class="grp-button fb_selectlink" onclick="FileBrowserDialogue.fileSubmit('{{ fileobject.url|escapejs }}');">{% trans "Select" %}</button>
                    <!-- select versions -->
                    {% if fileobject.filetype == "Image" and settings_var.ADMIN_VERSIONS %}
                        <div class="grp-pulldown-versions-container">
                            <a href="javascript://" class="grp-pulldown-versions-handler" title="{% trans "Versions" %}">&nbsp;</a>
                            <ul class="grp-pulldown-versions">
                                {% for version in settings_var.ADMIN_VERSIONS  %}
                                    {% version_setting version %}
                                    <li><a href="{% url 'filebrowser:fb_version' %}{% query_string '' 'filename' %}&amp;filename={{ fileobject.filename|urlencode }}&amp;version={{ version }}" title="">{{ version_setting.verbose_name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                {% else %}
                    &nbsp;
                {% endif %}
            </td>
        {% endif %}
        
        <!-- FILESELECT FOR CKEDITOR -->
        {% if query.pop == "3" %}
            <td class="fb_icon">
                {% selectable fileobject.filetype query.type %}
                {% if selectable %}
                <!-- select original -->
                <button class="grp-button fb_selectlink" onclick="OpenFile(ProtectPath('{{ fileobject.url|escapejs }}'));return false;">{% trans "Select" %}</button>
                <!-- select versions -->
                {% if fileobject.filetype == "Image" and settings_var.ADMIN_VERSIONS %}
                    <div class="grp-pulldown-versions-container">
                        <a href="javascript://" class="grp-pulldown-versions-handler" title="{% trans "Versions" %}">&nbsp;</a>
                        <ul class="grp-pulldown-versions">
                            {% for version in settings_var.ADMIN_VERSIONS  %}
                                {% version_setting version %}
                                <li><a href="" title="" onclick="OpenFile(ProtectPath('{% version fileobject version %}'));return false;">{{ version_setting.verbose_name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% else %}
                    &nbsp;
                {% endif %}
            </td>
        {% endif %}
        
        <!-- FILEICON -->
        <td>
            {% if fileobject.filetype %}
                <span class="fb_type {{ fileobject.filetype|lower }}">{% trans fileobject.filetype %}</span>
            {% else %}
                <span class="fb_type none">&mdash;</span>
            {% endif %}
        </td>
        
        <!-- THUMBNAIL -->
        <td class="fb_thumbnail">
            {% if fileobject.filetype == "Image" %}
                <a href="{{ fileobject.url }}" class="fb_viewlink"><img src="{{ thumbnail_version.url }}" title="{% trans 'View Image' %}" /></a>
            {% endif %}
        </td>
        
        <!-- FILENAME/DIMENSIONS -->
        {% if fileobject.filetype == "Folder" %}

            <td><a href="{% url 'filebrowser:fb_browse' %}{% query_string "" "q,dir,p" %}&amp;dir={{ fileobject.path_relative_directory|urlencode }}"><strong>{{ fileobject.filename }}</strong></a></td>
        {% else %}
            <td>
                <strong>{{ fileobject.filename }} | file</strong>
                {% if fileobject.dimensions %}
                    <br /><span class="small">{{ fileobject.dimensions.0 }} x {{ fileobject.dimensions.1 }} px</span><br clear="all" />
                {% endif %}
            </td>
        {% endif %}
        
        <!-- FOLDER -->
        {% if query.q and settings_var.SEARCH_TRAVERSE %}
            <td><a href="{% url 'filebrowser:fb_browse' %}{% query_string "" "dir,p" %}&amp;dir={{ fileobject.folder|urlencode }}"><strong>{{ fileobject.folder }}</strong></a></td>
        {% endif %}
        
        <!-- SIZE -->
        <td><span class="small">{% if fileobject.filesize %}{{ fileobject.filesize|filesizeformat }}{% else %}&mdash;{% endif %}</span></td>
        
        <!-- DATE -->
        <td><span class="small">{{ fileobject.datetime|date:"N j, Y" }}</span></td>
        
        <!-- EDIT -->
        <td>
            <ul class="grp-actions">
                <li class="grp-change-link"><a href="{% url 'filebrowser:fb_detail' %}{% query_string "" "p" %}&amp;filename={{ fileobject.filename|urlencode }}"><strong>{% trans "Change" %}</strong></a></li>
            </ul>
        </td>
        
    </tr>
{% endfor %}

 

filebrowser/templates/filebrowser/include/filter.html
{% load i18n fb_tags %}
<div id="filters" class="filter g-d-6 g-d-l">
    <div class="grp-filter">
        <div class="grp-pulldown-container">
            <a href="javascript://" class="grp-button grp-pulldown-handler">{% trans 'Filter' %}</a>
            <div class="grp-pulldown-content" style="display: none;">
                <div class="grp-module">
                    <div class="grp-row">
                        <label>{% trans "By Date" %}</label>
                        <select class="grp-filter-choice">
                            <option value="{% query_string "" "filter_date,p" %}">{% trans "Any Date" %}</option>
                            <option value="{% query_string "" "filter_date,p" %}&amp;filter_date=today"{% if query.filter_date == "today" %} selected="selected"{% endif %}>{% trans "Today" %}</option>
                            <option value="{% query_string "" "filter_date,p" %}&amp;filter_date=past7days"{% if query.filter_date == "past7days" %} selected="selected"{% endif %}>{% trans "Past 7 days" %}</option>
                            <option value="{% query_string "" "filter_date,p" %}&amp;filter_date=thismonth"{% if query.filter_date == "thismonth" %} selected="selected"{% endif %}>{% trans "This Month" %}</option>
                            <option value="{% query_string "" "filter_date,p" %}&amp;filter_date=thisyear"{% if query.filter_date == "thisyear" %} selected="selected"{% endif %}>{% trans "This year" %}</option>
                        </select>
                    </div>
                </div>
                <div class="grp-module">
                    <div class="grp-row">
                        <label>{% trans "By Type" %}</label>
                        <select class="grp-filter-choice">
                            <option value="{% query_string "" "filter_type,p" %}">{% trans "All" %}</option>
                            {% for extension in settings_var.EXTENSIONS %}
                            <option value="{% query_string "" "filter_type,p" %}&amp;filter_type={{ extension }}"{% if query.filter_type == extension %} selected="selected"{% endif %}>{% trans extension %}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>